### ISSUE TITLE
Feature: Add time into the date selectors

### ISSUE THREAD

**Issue by madpsy** [owntracks/frontend#10]
It would be really useful to be able to select a time window as well as date. This is because the traces can get very busy even within 1 day so being able to narrow down to a time window would help massively.

**Comment by linusg** [comment]
This will be in the upcoming v2 :+1:

**Comment by linusg** [comment]
Tempted to use a new date / time selector library fro this, https://chronotruck.github.io/vue-ctk-date-time-picker/ looks good.

**Comment by linusg** [comment]
This is implemented in https://github.com/owntracks/frontend/commit/7767a068751743a14a9770e00dff0fdc33ab531a, using the new date/time picker component mentioned above.

I published a new release [`v2.0.0-beta.4`](https://github.com/owntracks/frontend/releases/tag/v2.0.0-beta.4) which contains this change, please try it out (the image should build on Docker Hub shortly, you can of course build from source as well).

**Comment by madpsy** [comment]
Again, tested and working as expected. Thanks!
