### ISSUE TITLE
Improvement: Selection of Settings

### ISSUE THREAD

**Issue by cocker-cc** [owntracks/frontend#101]
Assume I have a **huge** amount of Data, and I want to visualize a particular Day in the Past.  First I have to select the older Timestamp, which instantly loads **all** the Data from this old Timestamp up to today.  This is very time-consuming and heavily challenges the CPU.

The Improvement would be: Let the User specify all the needed Settings without loading the Data in the Meantime.

**Comment by linusg** [comment]
Duplicate of #43.
