### ISSUE TITLE
Have frontend map utilize owntracks/+/+/info information for map display

### ISSUE THREAD

**Issue by troycarpenter** [owntracks/frontend#106]
For users that have cards created in the owntracks/+/+/info location, it would be nice if the frontend would utilize that information and display the username and photo for the various users.  It would be nice if that extended to the drop-down menus as well since the usernames don't necessarily match the display name.

**Comment by linusg** [comment]
https://owntracks.org/booklet/tech/json/#topics claims `owntracks/+/+/info` is for cards, and card info is already processed: 

![image](https://github.com/owntracks/frontend/assets/19366641/1379cad1-f92c-4b5a-890e-7e325fb8f77a)

https://github.com/owntracks/frontend/blob/f5389b84abbd4ab203502e7813252181835612ea/src/views/Map.vue#L233-L237

> It would be nice if that extended to the drop-down menus as well since the usernames don't necessarily match the display name.

The dropdowns are individual for users and devices, cards are per use/device combination only - I don't think that would make sense.

**Comment by troycarpenter** [comment]
The mobile app is showing it correctly, but that isn't happening on my frontend.  Here's a card:
![image](https://github.com/owntracks/frontend/assets/8419000/ea1e5776-7de4-4aee-9811-b5e7f67f33a9)
And here's the frontend:
![image](https://github.com/owntracks/frontend/assets/8419000/d08f14d3-447c-45a7-9dbb-336cfd89ccb4)

Is there a setting on the front end to enable this?

**Comment by jpmens** [comment]
@troycarpenter did you publish the CARD with a retained flag? (Otherwise, it might be possible that your open mobile app "saw" it but Frontend doesn't.)

If you subscribe to `owntracks/+/+/info` and see your CARD it'll be retained.

Is the image in the CARD very large?

**Comment by troycarpenter** [comment]
I will check.  The cards were created with the web tool, but none of the ones created for the users show up.  The images are pretty small, though.

**Comment by troycarpenter** [comment]
I have checked and all users info profiles are showing as retained.

Here's the card from my profile:
{
  "_type": "card",
  "name": "Troy",
  "face": "iVBORw0KGgoAAAANSUhEUgAAACgAAAAoCAYAAACM/rhtAAAAAXNSR0IArs4c6QAAEFtJREFUWEdVmPlvHPd5xj9z7X3vksublChK1GlZlhXbiu00sXLYSNK4aIMmDYIWQesCTYsiRX8oUPQfyC+9ECRF2qJBYLR1HMdNIDuJY1uWZd23xJviTS6Xe85es3MVM7NLOiTBPWbmO8+87/s87/N+hYW7l21BEBAlANH5h23ZILhvEQQb23a/dX+dP+eg0DnearXQ223+7Z/+hXyuSCodxbRs/viVPyUcjeHzK4iis64ItuCua9nOmrb76izu/lru6kiC4L63LMs9R1i495ELUBCcBSwH0R4g28I75qFxLnB+nIudO5Xyee5du8bcgxmyqR4++fRZLNvgztRDFhcXCEZDnHzmDPsOHMIfDHrrus/oAbTde9m762NZu8C8G4Iwd+eS7YBzMDhAbAek+yydEDmvzsqdSHbP0Wp1Vu8/5MDwGJlECsEWUSQZTWtiWTrttkGxVmBpc51AIk64t49EKuMu6wLtLO9GsYPGcjJn2e6hbraE2dsfdgB6J3aj5AWtC9J7Yudzq9nEZ1qItRrxQAgZASUQddZFkhX0ZgO9WUfXWxiGjmYaNLQmy6UC4b4BBkdHvccXhN1Ud27sfhY6gL3sW14EXbzOB0QXuZdS7zm6r24qAK1YJKgbRGUfuq4TCsex5SCCKCKIEs16BdmyadQrmLqG1mpiCxbVZpPZzXWkZIpTn3jaLSnTMr067MbQee+Wj8cD9+5zty855do5Za8mHHJ0ysCDattc/+ASWZ+fiZEhRNtGQkEMhIn3ZNEaTcy2RqVcxtQb7jWW0UY3dVqtBk2tRb2lsbCdIzo4zONnzrgAuoRxYmKalkeSbhSddM/cclLsFb0XMQmnFrzv9n5m7t0jrLc5ODSCLMrYhonZthBFCSEQRvb7sHWdtqFjtTVMrU29WaGtaW5dIgk0mxqmYNFQJIJ9QwwMDXWI40XLq3WvtEzDQJREB+BFJ64fq7cuqC5gJxI6olrH12p1iljA1A2stumyTpL97hKK7MM0dYx2G91o0zSabmQ1TcMSbHTLdNNqiODLZkmPjBIIBLySsnGPdRXDpapTdtM3Lzhs35UWj6XeF90kF3NbmMUiKX8Qn+zzYm16NRuKJECSMKtNBJ+CqbfBNNw01et1Gu06lXIJ3WyjGSZtJ8qmwdT6GgdPP8Hjp0/vEtC2LATRS7GXRcEB+IHdzXlHhXdp7xUr7Kyv0s7vkAyGCTsg/X4Unw9F8mEJMqIrnwKWaaKpVWSfH8swaDQa1NsN2kaLZrNOfqdIs62jWwZL2zkmTj/BSRegd71pGu69RYdApokkSwgPr7/nCrUH0mOtd8Ge7JQ2NmlsbRHzBYhGIkRiCbcxiJbs1mOrWkOQoN1wukqNcDCBWqtgiiKabYBk09Za7OSLlCoqhm1QqKkMHzvM5PETSKLcAeixWnI6j9NxnIg+uPauKzNuJ9mlu9UpWo/HW4uLaNs79KTTJJJxSqUSlz66gmVYpOMRsvEeJMsmEokhYGAhslnMs7q1Sa5YoKkbHNg/Sk8qQ6PRotVqUlCrtP0yZ559jsEOWVyhdiIoevprOWV0/+o7toPU6ZcOyL1IetLisCn3aBmtrHLh1j3Ov/+h04kZHRhkbn7OvdFAPM5nTx3mqROPY7Y0lrc3+dQ3XuHFl7/MvqFhnn7qDNdvXGVhZZUDY/v49KnjVMsFig2VF19+mUOHj3aytkfkbq8W7l15x2v/nZDudQ+PRbrW4kc//l8Uf4ivfuEcK3OzGM0momFz9/5dlpY2aCJSdnRyaoZ6q+lwhj/5/OdpVlWSoRA+WSSaSaJLCmqtxvs373BvfpFjI1n+4tuvcPzUaRyCdCVmj7TsRbAbva6T6dK9tb7Oa6/+BGVwkBefP8vK7CxzC4+49mCO6aUVDgwMMZrtxbAMvvq7XyEgwEt/+Vd8/cVzXLs3RbFapzeZ4NDYGKl4hHAkyOX7UzTKRZ6eGOHxZ84y/sQpZH/A678dyelqonDno1/tRrCrkx5VBJwOs371Bis3bjH6/LNksr2Y1QrFnSK5jR2qpRKWLiD5RL7/1tv85gffJ7eyzLf/9Xt85rETlAsFRN3TQEtWCESi9A/0cXdhkdz6GmdGR2nn8jz+e19i5ORjXi/e9QCezRNuX3IAesXpHfMcjUNiJ4rFqRnWb9wkNH6A7PAIMWwqxQp6q02zooKgUNOqXH+0yt/84dfIb+SY3lji/NWrnD2439UzE5FGs+6yOpxKUm2oFDfWidoSZrnGia+8xMDxI5gOa12vuacqwp1Lb3sy02GQJ5SO/nlekGaLyuwClUqVnGUzGE8TFwWa9QaNpsa7N25R397kr1/5c3pSWepqhZnFed6fnuXBwhRfefY5on4/kVCAliizUiljtKpU1tax6y0OnDrJ8OlTBOLR3zLKntxZCLcvvtUxrF1rtWe5vPZoY+bLVFeWaAoGhqqh5osUC0VXbh6tbfHll75AQpEJBSNUikU21QaJRJwf/PerPHl0kmQiTiadIhCL0xRsmk2V0mYOo9rg+OdfoHdyYk89OgaqK97CnQ/fdjuJZ6eE3Vbj1aNXh3a5RnlpnmqxQLWkUq+qlHdKrG5uEIlECNkSLcEmFApjKz7Uahv0OuF0Ets0CCsysWSGQDyMEvS5fdowDcqP1hk/+zQDJ499LK0dge64fOHWB+d3O8nHrf3HrXhA02lurDE1dY9aWaWUL7G4uUWmL0FANBk5cIxfnn+beCCJbmrMbeXpSYdJxzLEIkFqqsq+4TFiyTiiIiP5ZOqVClI0ysQnPkE8k+lY/z1P4GXPQrjx/s9tSXIE+uMG1UutBxKqy0tsTT9gZWUVXWtTrFR54pkzVHfWSfhl3r54jYmJMS5evIcsQE30E5Alvv6NP6JRyTM9e5+GKnL8wH63zxgCqOUyg0cnGT95imAo4kWwA8ptcS6dbYSbF37ekRnPgnss2jW2u8ZBXV9m9soVKsUSq7kt1EaDcCSC0WiRjEXZ2tyiWmo7BcHA8ADlUo1oIoKlWDxYWGH/0BgnxseQfQotx/GEFSI9KbKDw/QODBMIhD0f4BSV66o7ynL9/f9zU9zxW52RssPk3YnLprA4y+rdu2xv55leXGFqdQOfFKQ/GePg4AhtteH4azYLBTKpFKasUKpXWK2WqbWaDCYinDxyBF/AT72hIkUDxLK97rSXHRwhk+1HlhR3OJMc++b0YacOr7/3po0tgWC6QugSozP77vlpi7UHd8jPzVEolFhe32ApVyKuiJx7/lkKuRylfIGhQweRLYHFhUX8sRCtlsbqToVcYYdUJMThg4eQZZm2oRFIRon0pkEQCYXD9A0OkUhnXWfjOGnH5jkEFa69+zPbGXhcg9qhuDsy7YqlJ5qLt2+wdv8ODbVGvlhifmWLs08eZWJsmIX5Bzx4tEY0nObc7zzJm+cvuTWyubMNSoRGq0U6GWXfwAjJVNy9sRyNEErGHfPnDlyRaJz+4VFi8bTrAz2AtgfQcTK7g4oLVMDF3JmaHDbZhs7MlUusTU+T7e8lEI1w/NgRLv7yZxhmiNHRYWpqiasffETNsjl69CimXcOUYly+/pAvvvgZSiWVSqmELUJiYAAx6PcmYNt2Z5vebB+9g6MEgmEsy0AUFYSrv3nD1cHf3kHwkuuV5t5MvHDtKvM3rzC8fxxouPo2PbPE8599gXqlyfX3LmBKBjUNbFFkZmGRl770RULBELIkcvfmLdpti0RPimhfD5bkeFAPnOMBFb+fvsFhUul+FJ/iBsoF6IHxZuLu3kvXF3ogPTu+cvsmxeVFt/E7I+Xyo3l0/EwenmBlcYV6McfE5CTTs/NsllQeP36Ulc0dWq06J08cpbi1hYCfcCKKP5MCv4Jp6J1dDdGtvVg8SSY76Lp2RfEhXH7npx1KOCc4c8Vvj5vdudqZzBYfPEBdX6Fa3CEQDpDPbdIS/ETCYQq5PNX8NqGATSjWy/zyOolkkmarTb1W44kTk9i6gSwH0Z05pn+QtiyimHXiIf+ui1Z8AXr7smR6+wkEo3sA3TroiOWeZHs7DLZjSNsialll++YHqFurWEE/rUaT7WLJ1cBTJ46wvblNYSfHwNAIM4uPMEyLTLqPttYgEfKTiqXw+wKslWsImQyNtgaKwvhwhqDUtfoi0ViMweEx4skehI9+/Xp3f82zWu6457G43tCoqC2kWBZL8rGvP0Pu+kXuX3yHfE0llk6xsbFGTW0SDgcoFSrUqyXC8STJVJpaveHq2eFDB9jZWCPgC2IbAlULho5OYrRq1Foa4UQMn+hKNJYt4PP5yPb1k+kbQLj869fdmaTLCmfkc5xXrSVgCwpJZ0hq6I7wM5BJoaoqV19/leXZh2yUykTiYTY2cpiWSCoexjYsjp86yf2H00iihKFpDGV7KRfzREJRCqrG1cU1jjz1JGcem0QxNWbydRKSQSjsp78/y9baFoJPYt/YfoSPfvUTby525lrDRGgb1HSZhUerHDs8xvT8ots9JhMyfeNH2ag0WbpygfLaMpJfplJvuQKfr1RJRIMYuoniD6JWVCRJRpEUYkEZn+JzB/fL96fZaWt87nOf5tDkYebu30eTfPhiKW5du04q5Gd88jBf+OwL4GwSvPPW67Yi2JTVNjPNIKpmYleKVArbPHZ4nPVSFcG2OHtkP1YoydLcLKFWkdmL79IqFRwpJZJOMTMzTTIac/t5NBKjbZgokuRubTQqFfS2zqNcESmV4uCJQ6zlimQSMQZ6ksw7c04V9OI23/rm1+gbGqQhhohGwwiv/uIdu0eoIuSWiR14jIfrJWYX16jtrNEKpVmT0uzzN3hmfz+hdJaHC+tkUwne+K/vIW0ucKg3jezsBDgToG1hWM4+kYgsOd3AQrRB1w22y1WWyxXiPSmOHJkgmohT021C4QgRp9MOHMYnC/jLG8zPzvNQVTh+8gTCv//wP+20XSQoK6xqIVqhDBm5idwsUZGibFcbTPgbxIJBkkNjbNWhWKmzcPcKP33tfwhh8eRIH1HH0mttl/EOMZzo+WTZ3SUo1evMbO1Qamtksj2EUj1k4hH2DWSRFAVJbxMbOUw13MOQ1KC49ohqo4EwOInwrW9/x5Ytg5Ejx0gZdfpjCpmeLKVKhW0hweb8FId7AmQHR+kZ2c/q6hJ6tYyaW+MXl2/z+vlf0xv0uQD7k0nSPgVFEpAsi6wjJbrGfK7AnbVtsr0JjoyPIkZTCKbhpnh04hDq9gairTNVgahsMpmNExk4yObSQ4Qfvfam/cMLsxw/1MdppULcrDNy/DQXptd4484y2eYmzx0c4pPnXuSNN99kfP8YR8fHKS5P8XBth+/+8/dYWV1xRSAaChOQJHdvUUJ066+lt6g1NbLZHl5+4SyjY0PMrRd4990P0Z2moChke3o4+8xTvH7+AnIowLMTPbz05d/n6ttvIPzDd//RRtN474NLHBob4jt/9k3q5TzzhQaXp1aIG1XO/+wnroncyu/wt3/395z71HNsPJrnrWt3+OF//JhmcZtGU+1snwgYhrNL5RlfRyFGhgY59+xZ7j24R6la58DIIMlMGlMQuXnzrrMJ43bYeCZLcPxpPnl8kMWFBf7guZP8P/0g/PEMwcp9AAAAAElFTkSuQmCC"
}

**Comment by jpmens** [comment]
Your CARD data is valid JSON and works  for me on the current Frontend release:

![rabbit-10623](https://github.com/owntracks/frontend/assets/60706/28f5b92e-de19-4755-b9a8-dfbad76225d0)

One thing I ought to point out, but you've likely considered that, is to refresh your Web browser after publishing the card so that Frontend can get the new data.

**Comment by jpmens** [comment]
Something else you might want to test: can you see the card JSON when querying the Recorder API  directly?

```console
$ curl http://localhost:8883/api/0/last
```

**Comment by troycarpenter** [comment]
Just a follow up.  After upgrading to recorder 0.9.7 _and_ re-publishing all the user cards, both the recorder and frontend are now showing the correct username and photos.  Not sure if it was the combination of the upgrade and re-publish of the cards, but I suspect re-publishing the cards was probably sufficient.

**Comment by jpmens** [comment]
I assume it was the republishing as we've not released (and  you've not installed) a new Frontend. :-) 
Glad to hear it's working!
