### ISSUE TITLE
Timezone and ISO localtime at published location in Recorder API 

### ISSUE THREAD

**Issue by jpmens** [owntracks/frontend#108]
The Recorder API now provides [tzname and isolocal](https://github.com/owntracks/recorder/issues/444) via the API.

- `tzname` is the name of the time zone ($TZ) at the published location, e.g. `Europe/Amsterdam`
- `isolocal` is the display-capable local time at the published location

I’m not sure what Frontend should do with this data, but I wanted to make sure you’re aware of this. :-)

**Comment by linusg** [comment]
Happy to just add this to the popup, but it might need a new layout if it gets too crowded 😄
Gonna update my recorder to ensure I have this data and look into exposing it later today.

**Comment by jpmens** [comment]
Nice, thanks!
