### ISSUE TITLE
No data in frontend.

### ISSUE THREAD

**Issue by ozhound** [owntracks/frontend#111]
I've set this up and can connect to the frontend. This will show an empty map.

I can select layers and a date range but nothing is populating in the user selection drop down, only Show All

I've verified that  otrecorder is getting information from my Android client as i can see the files propagating in the storage/rec and storage/last directory which correlates to the setup in the android client. (being pushed via MQTT via the addon broker in home assistant)

I'm sure that I've not set up the config file properly and started with a blank config. I've since added items as per below, but it hasn't made a difference.

Can someone point me to a guide or advise what I've done wrong?

TIA

Oz

```// Here you can overwite the default configuration values
window.owntracks = window.owntracks || {};
window.owntracks.config = {
api: {
    baseUrl: "https://tracks.xxx.xx",
    fetchOptions: {
      credentials: "include",
        },
  },
  ignorePingLocation: false,
};```

**Comment by linusg** [comment]
Please check the network tab of you browser's devtools for authentication errors or other hints.

**Comment by ozhound** [comment]
There was an issue in the docker compose which was rectified, but there are no auth errors now in the network tab and the behaviour is still the same, nothing is shown

**Comment by gpion** [comment]
Same issue here
And the links in the "Configuration" section of [the docker Hub page ](https://hub.docker.com/r/owntracks/frontend) are broken
