### ISSUE TITLE
index.html with absolute links 

### ISSUE THREAD

**Issue by ckrey** [owntracks/frontend#118]
Since 2.13 the index.html uses absolute links to config.js, *.js, *.css, manifest.json and favicon.ico
which makes it impossible to use if frontend shall be used in a subdirectory e.g. https://server.example.org/owntracks/frontend
without manual patching

Example since 2.13:
```
    <script src="/config/config.js"></script>
```

pre 2.13:
```
<script src="config/config.js">
```

**Comment by ckrey** [comment]
The change in 998a971 fixes the absolute links for *.js, *.css, manifest.json and favicon.ico,
but not for `config.js`

```
...
    <script type="module" crossorigin src="./assets/index-C_JRePax.js"></script>
    <link rel="stylesheet" crossorigin href="./assets/index-DcjOgdvw.css">
  </head>
  <body>
    <noscript>
      <strong>We're sorry but OwnTracks doesn't work properly without JavaScript enabled. Please enable it to continue.</strong>
    </noscript>
    <div id="app"></div>
    <script src="/config/config.js"></script>
...
```

**Comment by linusg** [comment]
I tested it locally and got this:

```
$ grep config dist/index.html 
    <script src="./config/config.js"></script>
```

No idea why the CI output is different.

**Comment by linusg** [comment]
Ah, because I have that file locally (it's gitignored). How annoying.

**Comment by ckrey** [comment]
Even if I build the dist here, I don't get the expected result here.
Not sure if it helps, but I get the following warning when running `npm run build`.
```
vite v5.3.1 building for production...
<script src="/config/config.js"> in "/index.html" can't be bundled without type="module" attribute
```

**Comment by ckrey** [comment]
Thank you very much
