### ISSUE TITLE
Ignore ping? 

### ISSUE THREAD

**Issue by glynhudson** [owntracks/frontend#12]
A location `ping/ping` is showing up on the map in the frontend, this was not displayed in the recorder web view. It is possible to hide the ping? Or at least not include it in the autozoom? 

Related to https://github.com/owntracks/recorder/issues/195

**Comment by linusg** [comment]
> this was not displayed in the recorder web view

Right, it's filtered out:

https://github.com/owntracks/recorder/blob/9b695b8653375e196f05b139d989d5ede65e092f/docroot/table/index.html#L62-L64

This will be included in the upcoming v2.

**Comment by glynhudson** [comment]
Great! Is that recorder V2 or front-end V2? Which should I update?

**Comment by jpmens** [comment]
Frontend v2, but note "upcoming".

**Comment by linusg** [comment]
Implemented in https://github.com/owntracks/frontend/commit/87647c81d3b74ca3af6c1ef378f70124aa9c2f56.
