### ISSUE TITLE
is the accuracy displayed in the card?

### ISSUE THREAD

**Issue by tastytea** [owntracks/frontend#120]
there is a number in the card that *looks* like it is the accuracy, but it doesn't match the number in the default frontend (223 m versus 12 m). the circle around the point does look a lot more like 12 m too. also the app i record with isn't supposed to submit when accuracy is <= 100.

![screenshot_2024-07-03T09:29:11](https://github.com/owntracks/frontend/assets/3681516/201c6986-5bc6-4d6a-bb35-6969da42dc93)

what is the mystery number? 😊

**Comment by ckrey** [comment]
The number is the altitude in meters

**Comment by linusg** [comment]
Indeed, the accuracy is only exposed through the last known location's circle. Is it relevant enough for you to be shown on every single location popup?

**Comment by tastytea** [comment]
> Is it relevant enough for you to be shown on every single location popup?

no, it's only really relevant for me while calibrating my setup, i can get the data another way.

i was just assuming that it is the accuracy and thought it might be bugged 😊

**Comment by Kiwzi** [comment]
> Indeed, the accuracy is only exposed through the last known location's circle. Is it relevant enough for you to be shown on every single location popup?

I would like to see the accuracy on every point location popup.
Maybe make the information shown on popups configurable?
