### ISSUE TITLE
Missing download button?

### ISSUE THREAD

**Issue by itwasdolly** [owntracks/frontend#122]
I'm possibly stupid, but I can't find the download button on the map interface (like the one seen in the main docs). 

What am I doing wrong? Thanks!

<img width="1679" alt="Screenshot" src="https://github.com/owntracks/frontend/assets/129884341/98d9e6c6-d753-4407-b06f-8ed9eaf39ebc">

**Comment by linusg** [comment]
I removed it: https://github.com/owntracks/frontend/commit/8df1f86ab9257d1acd87644d54bf51c704b445c1

Please use the API or `ocat` (https://github.com/owntracks/recorder?tab=readme-ov-file#ocat) directly.
