### ISSUE TITLE
altitude difference (Höhenmetern)

### ISSUE THREAD

**Issue by RJGhugo** [owntracks/frontend#129]
Test with **altitude difference** (Höhenmetern):

- 1st day
09:00-11:00: 5km, **200m/200m**

- 2nd day
12:00-14:00: 3km, **25m/25m**
18:00-22:00: 18km, **30m/30m**

- 3rd day
06:00-07:00: 2km, **10m/10m**

**TOTAL**: 28km, **265m/265m**

**Selected Timeslot**: 2nd day, 12:00-14:00

Expected Result: 3km, **25m/25m**

The **altitude difference (Höhenmetern)** seems to be wrong. The **distance** right...

**Comment by linusg** [comment]
> Expected Result: 3km, 25m/25m

What's the actual result?

**Comment by RJGhugo** [comment]
Thanks I try to make a real example in the next few days...

**Comment by RJGhugo** [comment]
The track around the football field is 400m long.
My Android Phone, inside the pocket, measured 590m.
The sprint line (100m) was measured 120-130m.
[Laufbahn um Fussballfeld.zip](https://github.com/user-attachments/files/17350592/Laufbahn.um.Fussballfeld.zip)

**Comment by linusg** [comment]
I'm not sure what you're saying. Inaccuracies of your phone's GPS are not an issue of the frontend. You're the first person claiming there's a bug in the distance calculations, and until you can provide exact steps for me to reproduce it I'll close this issue.
