### ISSUE TITLE
Heatmap?

### ISSUE THREAD

**Issue by glynhudson** [owntracks/frontend#13]
The heatmap shown on the screenshots in the readme looks amazing. How was this created? I can't see an option in the frontend. 

Is this feature yet to be implemented? Keep up the good work, this front end UI looks really promising 👍

**Comment by linusg** [comment]
> The heatmap shown on the screenshots in the readme looks amazing.

Thanks! :smile:

> How was this created?

Internally it uses https://github.com/mourner/simpleheat

> Is this feature yet to be implemented?

It is already there! Click the `Layer Settings` dropdown and check ` Show location heatmap `.

**Comment by glynhudson** [comment]
>It is already there! Click the Layer Settings dropdown and check Show location heatmap

Doh! Don't know how I missed that. That's fantastic. Nice work
