### ISSUE TITLE
No Export Data from frontend

### ISSUE THREAD

**Issue by chr-ftw** [owntracks/frontend#130]
[owntracks/frontend](https://github.com/owntracks/frontend) (2.15.3)
[owntracks/recorder](https://github.com/owntracks/recorder) (0.9.8)
There is no export button in the top right corner, as shown in the readme of OwnTracks Frontend
![ot](https://github.com/user-attachments/assets/d0c4bd9f-b7c6-4190-8096-b352177fc7dd)

**Comment by linusg** [comment]
Duplicate of https://github.com/owntracks/frontend/issues/122.
