### ISSUE TITLE
Limit user access?

### ISSUE THREAD

**Issue by onexp** [owntracks/frontend#133]
Hey all,

quick question regarding frontend. I installed it using owntracks quicksetup with only 2 users (User A and User B). I limit mosquito.acl for User B to only read data from itself. Working so far.

But when I use frontend, User B still can access all data from User A. Is there any way to limit User B to only access data from User B?

Thank you.

**Comment by jpmens** [comment]
No, that is currently not possible nor is it a planned feature.

**Comment by linusg** [comment]
Even if the fontend provided artificial access control this would have to be implemented on the recorder's API side to actually be secure.
