### ISSUE TITLE
Read data from SQL

### ISSUE THREAD

**Issue by SanSanysch** [owntracks/frontend#136]
Hi, developers! More recently, i found your project. Admiring!
I have more than 10 years home automation and own MQTT server, and SQlite, but can change to mySQL for data from owntracks.
I didn't understand, is it really not realized in such a great idea read from SQL?
I don't want to install your recorder, because think SQL more functional. Sorry.
Can implement this in future versions?

**Comment by jpmens** [comment]
This project reads data from the Recorder API, and we've no intention of changing that.
