### ISSUE TITLE
Import a track to visualize the planned route

### ISSUE THREAD

**Issue by delta0815** [owntracks/frontend#137]
Hi all,

I am using your great Owntracks Frontend to visualize my upcoming marathon. I was wondering if there's a chance to upload the track so it will show where the track is going along?

Thanks for any ideas on how to do that :-)

Cheers,

quicky

**Comment by linusg** [comment]
IMO OwnTracks in general is for recorded data, not artificial data. There's nothing stopping you from importing a GPX file into the recorder's storage using https://github.com/owntracks/recorder/tree/master/contrib/gpx-to-rec however.

**Comment by delta0815** [comment]
Thanks alot and I do agree with your opinion. Do you know a similar tool which would be a better fit for my usecase?
