### ISSUE TITLE
Cannot view historic data?

### ISSUE THREAD

**Issue by glynhudson** [owntracks/frontend#15]
When I select a date time frame using the data pickers the trace data for that time period is not shown.

The data is available as shown on the Recorder web view:

![Screenshot 2019-09-29 at 01 51 46](https://user-images.githubusercontent.com/758844/65824148-eac21500-e25b-11e9-93e8-5f131e86c04d.png)

![Screenshot 2019-09-29 at 01 50 55](https://user-images.githubusercontent.com/758844/65824152-f9a8c780-e25b-11e9-8f11-4340eb4e3d16.png)

Inspecting the network page I can see that it looks the frontend successfully obtained the data for the requested period but the data was not displayed on the map:

![Screenshot 2019-09-29 at 01 57 04](https://user-images.githubusercontent.com/758844/65824186-a1be9080-e25c-11e9-9d08-b350df449b93.png)

I'm running the latest docker version of the frontend:
![Screenshot 2019-09-29 at 01 52 05](https://user-images.githubusercontent.com/758844/65824153-fd3c4e80-e25b-11e9-813f-d3681b156d95.png)

**Comment by linusg** [comment]
Hi @glynhudson,

Thanks for this rather extensive issue! Always good to see people investigating beforehand. :smiley:

I don't see an obvious reason for this just yet. Please try the following, in this order:

- Check your Layer Settings and ensure `Show location history (line)` is **checked** - weird stuff happens sometimes :smile:
- Check the `Console` tab in the devtools for warnings or errors
- Try if the same issue appears in Firefox. I have to admit I've not done a great job testing this thing in Chrome and other browsers and therefore had (& still have :disappointed:) browser-specific bugs. Now that OwnTracks UI seems to be getting a broader audience I'll make sure to do this properly.

**Comment by glynhudson** [comment]
Doh, only Latest Location was checked in Layer Settings. Checking lines/points/heat map all work now. I'm testing on Chrome and it seems to work fine 👍  

Although the app does take a long time to load and is unresponsive for 20s or so when I try to view multiple days of data. I guess this is since there is just so many points to load. Maybe in the future the app could choose to only load x number of points when viewing a large dataset over a long period. I would love to be able to view 1yr of data!  Thanks a lot for your help.

**Comment by linusg** [comment]
> Although the app does take a long time to load and is unresponsive for 20s or so when I try to view multiple days of data. I guess this is since there is just so many points to load. Maybe in the future the app could choose to only load x number of points when viewing a large dataset over a long period. I would love to be able to view 1yr of data!

Sure, being able to view a large amount of data is a priority. Some things to consider here:

- Hardware the recorder runs on. Depending how fast or slow it is, the response might take a while. 3.9s for 23MB of data (91302 entries) in my case.
- Hardware the browser runs on. Of course the browser needs to download and render all the data so sufficient download and computation speeds are required.
- Layers: the "line" and "heatmap" layers render without any noticable delay with the stated conditions , "points" however takes ages to render and freezes the UI. That's no surprise though - rendering 90k circles with outlines is computationally much more expensive than straight lines.
  I'd need to check if the recorder views suffer from the same issue when it comes to rendering points opposed to lines or if that's introduces in the additional Vue layer.

I guess noting this in a modal and asking for user approval if more than x points should be rendered as circles would be a good improvement.
For now, just turn off "points" and it should be no problem!

**Comment by DawidPietrykowski** [comment]
Just wanted to comment on large dataset rendering.
I think there are a few ways of dealing with this:
- Only render every x points, which would reduce the total number of points to render but still show most of the important information (since the dataset is big it shouldn't be a problem)
- Render only very simple dots or even squares for very large amount of data
- Allow selecting both start and end date before loading data (with the way it's now, I can't select a date far in the past without loading my 1.3mil locations)
- Only show points which are far apart, kinda like google does until you zoom in, might be hard to implement but would greatly improve user experience
Just my thoughts, I don't know vue or web dev in general so can't really help as of now but maybe some of these ideas are good.
Also, thanks for maintaining such a useful project!
