### ISSUE TITLE
Docker Hub build is broken

### ISSUE THREAD

**Issue by linusg** [owntracks/frontend#17]
Build on Docker Hub is currently broken, probably because the Dockerfile was moved to the `docker/` directory - I can build just fine locally using (from the repo root)

```
docker build -t owntracks-frontend -f docker/Dockerfile .
```

![image](https://user-images.githubusercontent.com/19366641/67626574-e7af4a00-f844-11e9-9608-2a8fd6f6f55f.png)

The link points to https://cloud.docker.com/redirect/?resource_uri=/api/audit/v1/action/0e7e8c53-979c-48cd-9c4d-7fa2a3e8db88/, which I can't view (I assume lacking permissions).

@jpmens it would be great if you could look into this!

**Comment by linusg** [comment]
> I assume lacking permissions

While we're at it, please update my permissions for this repo if possible, I just tried to set up Travis CI builds and I couldn't :confused:

**Comment by jpmens** [comment]
@linusg Done as requested

**Comment by linusg** [comment]
Thanks - not sure if I'm doing something wrong, but it still doesn't work (nor can I investigate the failed Docker Hub build):

![image](https://user-images.githubusercontent.com/19366641/68074011-1f127f00-fd8e-11e9-891a-fdbbb5d8f558.png)
