### ISSUE TITLE
Replace default Leaflet marker

### ISSUE THREAD

**Issue by linusg** [owntracks/frontend#2]
Replace this image:

![image](https://user-images.githubusercontent.com/19366641/54088714-a96a2680-4358-11e9-8f84-0cd5f54c2917.png)

with something more customized. Maybe even SVG with dynamic primary color?!

**Comment by amotl** [comment]
Dear @linusg,

through https://github.com/panodata/grafana-map-panel/issues/23, we just stumbled upon [Leaflet.BeautifyMarker](https://github.com/marslan390/BeautifyMarker), which might help to bring colorful iconic markers based on FontAwesome and Glyphicon icons to Leaflet.

With kind regards,
Andreas.

**Comment by linusg** [comment]
![image](https://user-images.githubusercontent.com/19366641/75755798-40c54800-5d27-11ea-9893-074d6e46efc6.png)
