### ISSUE TITLE
Subdirectory & relative paths

### ISSUE THREAD

**Issue by rjbrown99** [owntracks/frontend#21]
I have the UI hosted in a subdirectory, and the default yarn build makes every URL and include a relative path to the root.

IE

```html
<script src="/config/config.js"></script>
```

I want those paths to be relative to the directory I installed it in, so I had to modify `vue.config.js`.

```js
module.exports = {
  publicPath: '',
};
```
That fixes the yarn build to not include the leading slash.

```html
<script src="config/config/js"></script>
```

**Comment by linusg** [comment]
Hi @rjbrown99,

Thanks for this! According to https://cli.vuejs.org/config/#publicpath it might not be safe to use as default, but I'll investigate. Happy to add it to the Vue config file if nothing breaks, and a note in the readme otherwise.

**Comment by bencer** [comment]
I might be missing something else, but even rebuilding with publicPath: '' I'm seeing a call to /api/0/list that doesnt take into account my relative directory.

**Comment by linusg** [comment]
@bencer https://github.com/owntracks/frontend/blob/master/docs/config.md#apibaseurl
