### ISSUE TITLE
Calculdate distance traveled between two dates?

### ISSUE THREAD

**Issue by glynhudson** [owntracks/frontend#22]
Nice work on the front end, I've upgraded from an old version to the latest and it's developing really nice! 

Could I request a feature to be able to calculate distance travelled (in km or miles) between two dates? Is this calculation already possible using an owntracks API?

**Comment by jpmens** [comment]
The Recorder doesn't provide that information. Yet.

**Comment by jpmens** [comment]
Related to https://github.com/owntracks/recorder/issues/333

**Comment by linusg** [comment]
The frontend has a util function to calculate (using https://en.wikipedia.org/wiki/Haversine_formula) the distance between to coordinates (I believe leaflet includes one as well, but I added a custom one before I knew that 🙃)

https://github.com/owntracks/frontend/blob/bc3670df9919f77ba66e7b2d4db94b5a38784b77/src/util.js#L39-L67

It's being used separate a list of points into groups based on `config.map.maxPointDistance` (see https://github.com/owntracks/frontend/blob/master/docs/config.md#mapmaxpointdistance):

https://github.com/owntracks/frontend/blob/95613753a94bf29a7bd457c4c4eaea7276103ab8/src/store/getters.js#L50-L60

It's pretty accurate as well, from what I've seen at least:

https://github.com/owntracks/frontend/blob/95613753a94bf29a7bd457c4c4eaea7276103ab8/tests/util.test.js#L71-L104

---

So yeah, this would definitely be possible, and won't need to wait for the recorder to support something like this. Just need to create a sum for the distance between all subsequent points.

Do you want to try submitting a PR?

**Comment by linusg** [comment]
I implemented this in https://github.com/owntracks/frontend/commit/4078597f7a935b5350ecdd7917b46df8ae78c670 - it looks like this:

![image](https://user-images.githubusercontent.com/19366641/74067676-af95d680-49f1-11ea-8454-fb4893786bb0.png)

Enabled by default, disable by setting the `showDistanceTravelled` config option to `false`.

The generated string respects the configured `locale` when it comes to the decimal separator, but only m/km are supported for now - happy to add a config option for the preferred distance unit, but that should affect speed as well. Not a priority for me, I use metres.

Oh, and someone should do a US-specific translation file, I spell "travelled" with two L :wink:

**Comment by linusg** [comment]
Released in [https://github.com/owntracks/frontend/releases/tag/v2.0.0-beta.10](v2.0.0-beta.10). Expect a built image on Docker Hub shortly.

I guess it's time to drop the `-beta.x` at some point...

**Comment by linusg** [comment]
Ah, and @jpmens - I'll happily throw out all the frontend code for the calculation if the recorder API will have this at some point :smile:

**Comment by jpmens** [comment]
If we start at a particular time stamp and hop from one position to the next and _haversine()_ all the things it shouldn’t be too difficult, but seeing you’ve already done all the work in the frontend we’ll put this on a bit of a backburner.

(Seriously flat out now, so https://github.com/owntracks/recorder/issues/333 has to wait, but it’s not too hard I think, depending on how you’d want to see the data in the API.)

**Comment by glynhudson** [comment]
Wow, nice work! 👍  It works really great and seems pretty accurate:

![Screenshot 2020-02-08 at 03 40 10](https://user-images.githubusercontent.com/758844/74078629-b853d000-4a24-11ea-9bf3-9eed144cdfd3.png)

I noticed when trying to calculate distance over several months (lots of data) sometimes the app would crash. Refreshing the page and waiting a while would usually result in the calculation working.

**Comment by glynhudson** [comment]
The distance value sometimes flows off the page, changing "Distance travelled" test to just "Distance" would solve this?

**Comment by linusg** [comment]
> I noticed when trying to calculate distance over several months (lots of data) sometimes the app would crash. Refreshing the page and waiting a while would usually result in the calculation working.

Yeah, that's just how it is. The calculation is not exactly cheap, and since we're just doing everything in the main thread, when having a lot of points the page freezes (definitely "expected") and the browser might decide to kill the ongoing loop.

To be fixed in https://github.com/owntracks/frontend/issues/24.

> The distance value sometimes flows off the page, changing "Distance travelled" test to just "Distance" would solve this?

I [changed](https://github.com/owntracks/frontend/commit/f4262efaa44b374de356245d41424304a1004912) it to just show the distance and have the additional label as a `title`.

**Comment by linusg** [comment]
> To be fixed in #24.

Closed this as wontfix, see my comment there. The distance calculation itself doesn't seem to be the cause of your performance issue.

**Comment by linusg** [comment]
I did play around with https://github.com/GoogleChromeLabs/worker-plugin though, so if web workers should come up again in the future I'll already have a few ideas.
