### ISSUE TITLE
First load of UI always starts at lat,lon=0.0

### ISSUE THREAD

**Issue by glynhudson** [owntracks/frontend#23]
I've noticed in the last couple of versions the auto center does not seem to automatically work, the map starts zoomed into lat,long=0. Not a big issue, but could catch some users out since no data is shown until the user zooms out: 

![Screenshot 2020-02-08 at 03 45 02](https://user-images.githubusercontent.com/758844/74078706-6fe8e200-4a25-11ea-97d0-5ef23c125efd.png)

![Screenshot 2020-02-08 at 03 45 17](https://user-images.githubusercontent.com/758844/74078709-770ff000-4a25-11ea-81e1-9ae994fe74fe.png)

**Comment by linusg** [comment]
> First load of UI always starts at lat,lon=0.0

That's expected:

https://github.com/owntracks/frontend/blob/f4262efaa44b374de356245d41424304a1004912/src/config.js#L20-L23

https://github.com/owntracks/frontend/blob/master/docs/config.md#mapcenterlat

I don't think we ever had auto-fitting after loading data in v2, what's the behaviour you'd like to see?

- Should only the initial loading of data trigger auto-fitting once, or every subsequent loading as well?
- Should every change to layer visibility trigger auto fitting?

That'd probably mean getting rid of the options mentioned above, as they'll be useless.

**Comment by glynhudson** [comment]
I guess ideal behaviour would be to center the map and auto zoom to fit the
data. The recorder map preview does this very well.

- sent from my mobile device

**Comment by linusg** [comment]
Implemented in https://github.com/owntracks/frontend/commit/3b18ab58edcabaa471cfd6c23cd05b60449dfc27, in a very lazy way: whenever `lastLocations` or `locationHistory` change, `fitView` is being called.
