### ISSUE TITLE
Make distance traveled calculation optional? 

### ISSUE THREAD

**Issue by glynhudson** [owntracks/frontend#27]
The new distance travelled feature is *really awesome*, however I think it would be a good idea to make the feature optional, since when trying to display lots of data over a long period the app now crashes while previously it didn't. This is presumably (and understandably!) due to the calculation intensive job of calculation distance. 

Maybe it could be disabled by default, then enabled with a toggle whenever distance calculation is required?

**Comment by linusg** [comment]
Are you not reading the comments I'm making in the issues you're involved in?

I'd really appreciate that.

---

> **I think it would be a good idea to make the feature optional**

From the original issue that _you_ opened: https://github.com/owntracks/frontend/issues/22#issuecomment-583626431

> Enabled by default, disable by setting the `showDistanceTravelled` config option to `false`.

---

> **This is presumably (and understandably!) due to the calculation intensive job of calculation distance.**

I still doubt that, unless you're using a rather weak machine. If you want it fixed, open a new issue with details about the browser, OS and machine you're using, how many location points are being loaded and ideally how long the calculation takes (timestamp1 - timestamp2, `console.log`).

See https://github.com/owntracks/frontend/issues/24#issuecomment-593139166:

> Actually this doesn't seem to be a problem - some measurements:
>
> ```
> 15261 0.027
> 15261 0.026
> 15261 0.031
> 162238 0.251
> 162238 0.256
> 162238 0.225
> ```
>
> First column is the loaded location history length, second column is execution time of `_getDistanceTravelled` in seconds.

I even wrote a comment in the original thread to inform you about that: https://github.com/owntracks/frontend/issues/22#issuecomment-593139982

> > To be fixed in #24.
>
> Closed this as wontfix, see my comment there. The distance calculation itself doesn't seem to be the cause of your performance issue.

**Comment by linusg** [comment]
@glynhudson I implemented some more logging in https://github.com/owntracks/frontend/commit/b3fdf1eabefcd15f8ed8be3bb64d14ee20c7883a, so if you build from master or use the Docker Image with the `latest` tag, you should be able to see how long this calculation really takes 🙂
