### ISSUE TITLE
LTileLayer adding wms layer 

### ISSUE THREAD

**Issue by serbasii** [owntracks/frontend#29]
Hi! i want to custom layer from server as wms. how can i?
e.g
```vue
LTileLayer: {
    baseUrl: "*****/geoserver/vega-api/wms?",
    layers: [
      {
        name: "Municipios",
        visible: true,
        layers: "vega_api:municipio"
      },
      {
        name: "Estados",
        visible: true,
        layers: "vega_api:estado"
      }
    ]
  }
```

**Comment by linusg** [comment]
> Hi! i want to custom layer from server as wms. how can i?

Currently you can't, but I'll happily accept a pull request that adds this functionality.

Docs are here:
- https://vue2-leaflet.netlify.com/components/LWMSTileLayer.html
- https://leafletjs.com/examples/wms/wms.html

**Comment by serbasii** [comment]
I added the feature. It can be "pull request" for a few days.
