### ISSUE TITLE
Map not loading at all

### ISSUE THREAD

**Issue by Mallinanga** [owntracks/frontend#32]
vue-cli-service build runs successfully but the map does not load at all.
In fact when I inspect the <main> element in html, it's completely empty.

**Comment by linusg** [comment]
Look in the browser's console and network information for errors. I can't debug this with so little info.

**Comment by Mallinanga** [comment]
No errors at all in the browser's console. API calls to ot-recorder are working fine. Fields are populated correctly. It seems as if just the vue map component is not loading at all.

**Comment by linusg** [comment]
I suggest you do a development build then and have a look using the Vue devtools: https://github.com/vuejs/vue-devtools#installation
