### ISSUE TITLE
manually building with yarn && frontend dist build && lower level api for old mobile (>2.1) phones

### ISSUE THREAD

**Issue by compusolve-rsa** [owntracks/frontend#33]
Hi, 

Thanks for the potentially very cool project. A couple of major issues needing some attention.

**manually building with yarn

I got the recorder app (ot-recorder via ppa) running on ubuntu without docker. Tried docker but the setup gives no clue how to configure the docker container to the installed mosquitto service on ubuntu. 

**frontend dist build

After that I tried to download and build the front end with yarn. Oh wow, troublesome. Peer dependencies fail on yarn install, and when I try to satisfy them one by one, it just gets worse.

Is there a cleaner way to build a dist of frontend I can slap into www/html? Maybe a direct download to a prebuilt dist?

**lower level api for old mobile (>android2.1) phones

The android app works well but fails to install on older devices. I got an old cm11 phone lying around that would be great as a tracking device, but a parsing error keeps popping up when I try to install the app.

Any help most welcome.

Regards

Lee

**Comment by linusg** [comment]
> **manually building with yarn
> 
> I got the recorder app (ot-recorder via ppa) running on ubuntu without docker. Tried docker but the setup gives no clue how to configure the docker container to the installed mosquitto service on ubuntu.

I don't see how that's connected to yarn? Seems like you should discuss this in https://github.com/owntracks/recorder instead.

> **frontend dist build
> 
> After that I tried to download and build the front end with yarn. Oh wow, troublesome. Peer dependencies fail on yarn install, and when I try to satisfy them one by one, it just gets worse.

Happy to look into that but need complete logs, OS details etc. Still works on my machine :tm:

```
➜  frontend git:(34cc489) rm -rf node_modules  
➜  frontend git:(34cc489) yarn && yarn build
yarn install v1.22.4
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.2.9: The platform "linux" is incompatible with this module.
info "fsevents@1.2.9" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@2.1.2: The platform "linux" is incompatible with this module.
info "fsevents@2.1.2" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning " > vue2-leaflet@2.5.2" has unmet peer dependency "@types/leaflet@^1.5.7".
warning " > babel-core@7.0.0-bridge.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "babel-jest > babel-preset-jest > @babel/plugin-syntax-object-rest-spread@7.2.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning " > @vue/eslint-config-prettier@6.0.0" has unmet peer dependency "prettier@>= 1.13.0".
warning " > babel-jest@25.2.6" has unmet peer dependency "@babel/core@^7.0.0".
warning "babel-jest > babel-preset-jest@25.2.6" has unmet peer dependency "@babel/core@^7.0.0".
warning "babel-jest > babel-preset-jest > @babel/plugin-syntax-bigint@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning " > eslint-plugin-prettier@3.1.2" has unmet peer dependency "prettier@>= 1.13.0".
warning " > moment-locales-webpack-plugin@1.2.0" has unmet peer dependency "webpack@^1 || ^2 || ^3 || ^4 || ^5".
warning " > sass-loader@8.0.2" has unmet peer dependency "webpack@^4.36.0 || ^5.0.0".
[4/4] Building fresh packages...
Done in 34.29s.
yarn run v1.22.4
$ vue-cli-service build

⠹  Building for production...Browserslist: caniuse-lite is outdated. Please run next command `yarn upgrade`
⠸  Building for production...

 WARNING  Compiled with 3 warnings                                                                                                                                                            14:19:59

 warning  

asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
This can impact web performance.
Assets: 
  js/chunk-vendors.e58e6f49.js (869 KiB)

 warning  

entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.
Entrypoints:
  app (972 KiB)
      css/chunk-vendors.020597aa.css
      js/chunk-vendors.e58e6f49.js
      css/app.9c79704f.css
      js/app.24b831c5.js


 warning  

webpack performance recommendations: 
You can limit the size of your bundles by using import() or require.ensure to lazy load some parts of your application.
For more info visit https://webpack.js.org/guides/code-splitting/

  File                                   Size              Gzipped

  dist/js/chunk-vendors.e58e6f49.js      869.42 KiB        256.19 KiB
  dist/js/app.24b831c5.js                43.67 KiB         11.99 KiB
  dist/config/config.example.js          0.13 KiB          0.11 KiB
  dist/css/chunk-vendors.020597aa.css    48.72 KiB         10.96 KiB
  dist/css/app.9c79704f.css              10.36 KiB         2.43 KiB

  Images and other types of assets omitted.

 DONE  Build complete. The dist directory is ready to be deployed.
 INFO  Check out deployment instructions at https://cli.vuejs.org/guide/deployment.html
      
Done in 26.66s.
```

> **lower level api for old mobile (>android2.1) phones
> 
> The android app works well but fails to install on older devices. I got an old cm11 phone lying around that would be great as a tracking device, but a parsing error keeps popping up when I try to install the app.

That doesn't belong here either, please open a separate issue in https://github.com/owntracks/android.

**Comment by compusolve-rsa** [comment]
Update on front-end build. I had to downgrade node 14 to node 10 to get the front-end to build. There were unmet peer dependencies but it give output a dist.

**Comment by linusg** [comment]
> I had to downgrade node 14 to node 10 to get the front-end to build.

Thanks for the feedback. I'm using 12.16.3 on my machine and the Docker image uses 10.x - so it might be good to specify a version range in `package.json` and eventually investigate how we can make it build with 14.x.

**Comment by compusolve-rsa** [comment]
Two questions.

Do you have cli instructions how to mimick your install of node and yarn? Would be great to be version specific.

Has anyone used nodesource for installation of node?
