### ISSUE TITLE
BaseURI to support OwnTracks not running at domain root

### ISSUE THREAD

**Issue by metal450** [owntracks/frontend#4]
This is amazing...SOOO much nicer than having to remember the custom URL scheme to filter data in the default recorder! :)

Just one issue: in my setup, I use a reverse proxy to serve the recorder under a subpath of the domain (i.e. https://domain.com/owntracks).  Although the default UI works, this retrieves no data.

The fix is easy: prepend all the '/api/...' URLs in static/main.js with a baseURI.

**Comment by linusg** [comment]
I'm aware of this issue. I'm currently basically rewriting the whole Project for make use of modern ES6 and Vue's single file components - along with other improvements.
I'm pretty sure this is fixed already, I simply had no time publishing my updates so far (also, I think the heatmap is broken ATM). I'll let you know once it's done.

Thanks for taking the time to open an issue though, much appreciated!

**Comment by metal450** [comment]
Awesome, thanks!

**Comment by linusg** [comment]
Implemented in https://github.com/owntracks/frontend/commit/4d971d57f705cbd0c206779d4c0ea96f356732ff.

The configuration object key `api.baseUrl` will be used, it defaults to the current protocol and host.

https://github.com/owntracks/frontend/blob/4d971d57f705cbd0c206779d4c0ea96f356732ff/src/config.js#L12-L15
