### ISSUE TITLE
[Feature] elevation change calculation

### ISSUE THREAD

**Issue by pchampio** [owntracks/frontend#51]
Pretty much the same sutff as the calculation of distances, but for the +- elevation.

**Comment by linusg** [comment]
Nice idea :)

**Comment by linusg** [comment]
This is what I came up with:

![image](https://user-images.githubusercontent.com/19366641/108421651-c3dff680-7235-11eb-80d1-0031a40cb8d7.png)

**Comment by pchampio** [comment]
Damm that was fast!
Keep the good work, you rock!

**Comment by 3rdStng** [comment]
Love this, but how can I change it to imperial numbers?

**Comment by linusg** [comment]
Until someone implements #103 you can't.

**Comment by 3rdStng** [comment]
Thank you. I saw that post too, but honestly wasn't sure if that was an upcoming feature or if there was some work around I could do today. I've been digging through that rabbit hole for a while this afternoon
