### ISSUE TITLE
The frontend is only showing up once, then switching back to standard view on reload

### ISSUE THREAD

**Issue by streiman** [owntracks/frontend#52]
I have a weird issue and I guess it is no bug in owntracks/frontend, but in my nginx configuration. But I am really lost and hoped that the experts here can point me to a solution. If I open owntracks on my private domain <mydomain> it shows the nice map of owntracks/frontend.

But all selections like daterange, which are parsed to the domain are ignored, so I see always everything. And when I press i.e. reload, the old interface is loaded. It seems that frontend is only shown using the domain without anything behind it like the coordinates. That seems strange to me but I can't find the reason. 

I installed owntracks first and it works. I wanted a nicer frontend and installed owntracks/frontend using docker-compose following the instructions:

```
owntracks-ui:
     image: owntracks/frontend
     ports:
      - "9122:80"
     volumes:
       - /home/andi/owntracks/ui-data/config.js:/usr/share/nginx/html/config/config.js
     environment:
       - SERVER_HOST=otrecorder # the UI needs to know where the recorder is
       - SERVER_PORT=8083
     restart: unless-stopped
```

I had to change the "ports" from "80:80" like mentioned in the docs because otherwise I got an error, that the port 80 is already in use.

I think the problem is in my nginx reverse proxy configuration which looks like this:

```
server {
    server_name  <mydomain>;

    # Proxy and upgrade WebSocket connection
    location /ws {
        rewrite ^/owntracks/(.*)    /$1 break;
        proxy_pass      http://127.0.0.1:8083;
        proxy_http_version  1.1;
        proxy_set_header    Upgrade $http_upgrade;
        proxy_set_header    Connection "upgrade";
        proxy_set_header    Host $host;
        proxy_set_header    X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location / {
        proxy_pass      http://127.0.0.1:8083/;
        proxy_http_version  1.1;
        proxy_set_header    Host $host;
        proxy_set_header    X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header    X-Real-IP $remote_addr;
    }

    # OwnTracks Recorder Views
    location /view/ {
         proxy_buffering         off;            # Chrome
         proxy_pass              http://127.0.0.1:8083/view/;
         proxy_http_version      1.1;
         proxy_set_header        Host $host;
         proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
         proxy_set_header        X-Real-IP $remote_addr;
    }
    location /static/ {
         proxy_pass              http://127.0.0.1:8083/static/;
         proxy_http_version      1.1;
         proxy_set_header        Host $host;
         proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
         proxy_set_header        X-Real-IP $remote_addr;
    }

    # HTTP Mode
    location /pub {
        #auth_basic              "OwnTracks pub";
        #auth_basic_user_file    /usr/local/etc/nginx/owntracks.htpasswd;
        proxy_pass              http://127.0.0.1:8083/pub;
        proxy_http_version      1.1;
        proxy_set_header        Host $host;
        proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header        X-Real-IP $remote_addr;

        # Optionally force Recorder to use username from Basic
        # authentication user. Whether or not client sets
        # X-Limit-U and/or uses ?u= parameter, the user will
        # be set to $remote_user.
        proxy_set_header        X-Limit-U $remote_user;
    }

    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/<mydomain>/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/<mydomain>/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
    }
```

I would really appreciate any help of the experts here.

**Comment by linusg** [comment]
You changed the frontend's exppsed port to 9122 but that's not mentioned anywhere in the nginx config, so I'm not sure how this would work at all?! to clarify, you want the frontend at `<my domain>/` with no added path?

**Comment by streiman** [comment]
I would also use an added part or another subdomain - I just would love to get it working.

**Comment by linusg** [comment]
I'd suggest using the correct port for a start :)

**Comment by streiman** [comment]
Ok, the correct port didn't work, because it was in use. But your first answer gave me the right direction:

I added a new subdomain for the frontend in the nginx-configuration

`server {
    server_name <newsubdomain>;
    location / {
            proxy_pass http://127.0.0.1:9138;
    }

    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/<mydomain>/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/<mydomain>/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
}
`
Well, now it works fine. Thank you for your good work!
