### ISSUE TITLE
Date/time filtering is not working

### ISSUE THREAD

**Issue by orxaz** [owntracks/frontend#54]
Hi.

When I try to filter in a from-to date-time mode, all collected locations are shown, not only the ones on the selected range:
![image](https://user-images.githubusercontent.com/39266145/111487148-678acc80-8738-11eb-96f4-5c072865ce8b.png)

Am I doing something wrong?

**Comment by linusg** [comment]
That's a US date format, i.e. the 6th March 2021 - which is within the selected time range. You can change the locale, see [here](https://github.com/owntracks/frontend/blob/master/docs/config.md#locale).

**Comment by orxaz** [comment]
Sorry @linusg , and thanks for the aclaration.
My bad, did not realized that different months was selected :facepalm:
