### ISSUE TITLE
Document changing of application path

### ISSUE THREAD

**Issue by Toothwitch** [owntracks/frontend#58]
Hi all,

i would like to change the path of my frontend instance.
I observed similar behaviour as #32 when i deployed the dist folder content into a subfolder of my webroot. 
Development Server worked perfectly fine. The only difference was the path. When deployed directly into a webroot there were also no issues at all.

I tried changing the public path with this guide
https://cli.vuejs.org/guide/deployment.html
but had no positive result. 
Would someone be able to look into this and document this setting?

**Comment by linusg** [comment]
https://github.com/owntracks/frontend/blob/master/docs/config.md#routerbasepath
