### ISSUE TITLE
No line segment drawn on position update

### ISSUE THREAD

**Issue by MaxWipfli** [owntracks/frontend#60]
When the position is updated while viewing the map, the line is not extended to connect to the last segment.

**Comment by linusg** [comment]
Oh hi :D
There's an option for that, but it's disabled by default: https://github.com/owntracks/frontend/blob/master/docs/config.md#onlocationchangereloadhistory

**Comment by linusg** [comment]
... although I think I'll enable it by default, the reason why it was disabled no longer applies AFAICT.
