### ISSUE TITLE
Can't find servers name

### ISSUE THREAD

**Issue by josefv2** [owntracks/frontend#70]
I'm changing the location services provider so it's not Google anymore, I'm deegoogling. Following this guide, point 3: https://www.reddit.com/r/degoogle/comments/cldohl/how_to_degoogle_lineageos_in_2019/

As all that providers are not good enough I was suggested to use Owntracks instead, however after reading the booklet and installing your app I can't find any info of your server, so I don't know which one should I put. What is the direction of your servers to use them for location services?

**Comment by jpmens** [comment]
We don't provide servers. The OwnTracks project provides software for you to use free of charge with servers that you set up and configure yourself.
