### ISSUE TITLE
Noob Guide

### ISSUE THREAD

**Issue by 0xspade** [owntracks/frontend#74]
Hi,

Is there anyone out there that can teach me how to establish this? I am having trouble setting this up (mqtt, owntracks recorder, and owntracks frontend). I can't get it to work. a noob guide tutorial for docker cli will be helpful.

**Comment by linusg** [comment]
You don't necessarily need MQTT, HTTP is enough.

> a noob guide tutorial for docker cli will be helpful.

That's out of scope for this project, plenty of those exist online.

**Comment by 0xspade** [comment]
>That's out of scope for this project, plenty of those exists online.

Can't find any. some of them are outdated.

>You don't necessarily need MQTT, HTTP is enough.

What do you mean by this? owntracks recorder and frontend only? Is it possible to connect my kid's device to my self-hosted owntracks?

**Comment by 0xspade** [comment]
solved ;)

**Comment by gitc23** [comment]
Hey @0xspade, I just wrote a [guide](https://www.shmostert.com/owntracks-recorder-frontend-setup/) that shows the setup from start to finish with all steps that worked for me, maybe you find it helpful :)
