### ISSUE TITLE
Websockets and openstreetmaps

### ISSUE THREAD

**Issue by 0xspade** [owntracks/frontend#77]
Yesterday, my owntracks frontend is running fine, but now, the websockets and openstreetmaps are 403 forbidden. I wonder why

Can someone help me out?

![owntracks](https://user-images.githubusercontent.com/18681023/159148814-d0af8d5c-82bb-4bb0-8e10-ddc1ee4fe30c.JPG)

**Comment by linusg** [comment]
Impossible to debug with this little information.
