### ISSUE TITLE
Doesn't load map element

### ISSUE THREAD

**Issue by atjn** [owntracks/frontend#89]
I am running a fairly standard setup where the frontend is served by [Caddy](https://caddyserver.com/) on https://[host]/frontend. I have not changed any config settings.

When I open the app, everything works as expected, except that the map is missing. The entire `div.vue2leaflet-map` element is just never added to the DOM.

I have tested this against the official `docker.io/owntracks/frontend` image, which does load the map. My setup loads the exact same resources as the official one, and I have no server errors, no console errors, all the information from the server is loaded correctly. In other words, as far as I can tell, the app is working perfectly fine.

Here's a quick video of what the app looks like:
[frontend.webm](https://user-images.githubusercontent.com/20535393/192247372-b12b04f4-9e78-4f03-b16e-d8759e0c0bfa.webm)

My setup is also running in a Docker container, and you can check out the configuration here:
https://github.com/atjn/docker-easy-owntracks/blob/d8d06a7a89c6f3029809314760a565c3eccd3435/Dockerfile#L36

I see the same issue in both Firefox and Edge.

Do you have any idea what is going on here? Any help is much appreciated, thanks!

**Comment by linusg** [comment]
Same as https://github.com/owntracks/frontend/issues/58 perhaps? (and by extension, https://github.com/owntracks/frontend/issues/32)

Judging by your Caddyfile you deploy the frontend at `/frontend/`, and since the app uses a [client-side router](https://github.com/owntracks/frontend/blob/main/src/router.js) that renders the map view at `/` relative to the `router.basePath` config, you'll need to change that.

**Comment by linusg** [comment]
(this seems unnecessary at first given the frontend still only has a single page, but was done in anticipation of adding different view types at different URLs - e.g. `/` is the map, `/devices` lists devices, etc. - just haven't made use of that yet)

**Comment by linusg** [comment]
Relevant part of the config docs: https://github.com/owntracks/frontend/blob/main/docs/config.md#routerbasepath

**Comment by paclg** [comment]
Ahhh I lost some hours on this, :-( but it's ok now, thank you for your nice work 👍
